#name: test on ubuntu laravel app
#on:
#  push:
#    branches:
#      - test
#
#jobs:
#  app-deploy:
#    name: Laravel App Deployment
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Run Remote/Artisan Commands
#        uses: appleboy/ssh-action@v0.1.6
#        with:
#          host: ${{ secrets.VPS_HOST }}
#          username: ${{ secrets.VPS_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd /var/www/laravel
#                  php artisan migrate --force
#                  php artisan optimize
#
